// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslr-0BpjxUOZzirpx_JKhkkBHW6o-AFc',
    appId: '1:471694942421:web:96d6fd8211550757c2425c',
    messagingSenderId: '471694942421',
    projectId: 'brew-crew-7f809',
    authDomain: 'brew-crew-7f809.firebaseapp.com',
    storageBucket: 'brew-crew-7f809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhoTdorKpWOia27AjHyt0bT_eKJup6Yos',
    appId: '1:471694942421:android:c0064a5d308968e1c2425c',
    messagingSenderId: '471694942421',
    projectId: 'brew-crew-7f809',
    storageBucket: 'brew-crew-7f809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6oJ_q1QbCSpZICIKbN76zENiyfGNOiA',
    appId: '1:471694942421:ios:51233dcdaf0eb740c2425c',
    messagingSenderId: '471694942421',
    projectId: 'brew-crew-7f809',
    storageBucket: 'brew-crew-7f809.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA6oJ_q1QbCSpZICIKbN76zENiyfGNOiA',
    appId: '1:471694942421:ios:0488782214906d9fc2425c',
    messagingSenderId: '471694942421',
    projectId: 'brew-crew-7f809',
    storageBucket: 'brew-crew-7f809.appspot.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
